# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------
QT+=core gui widgets
TEMPLATE = app
TARGET = bank_saving
DESTDIR = ./x64/Debug
CONFIG += debug
LIBS += -L"."
PRECOMPILED_HEADER = stdafx.h
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(bank_saving.pri)
